### PR TITLE
Bump to 0.0.3

### PR DESCRIPTION
**Pull request by rhatdan**
Update the changelog

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@4383 Ok, I pushed the tag on master and published the release.  Is everything ok now?

**Comment by 4383** [comment]
@rhatdan nice! it's ok now.

https://pypi.org/project/podman/0.0.3/

**Comment by 4383** [comment]
@rhatdan Another interesting way to manage `ChangeLog` in the next release could be to use `reno` to obtain a more focused and beautiful changelog instead of only list commits.

https://pypi.org/project/reno/

Reno is compatible with `pbr` too.

Thoughts?

**Comment by rhatdan** [comment]
You would know far better then me.  I am no PYPI expert.

**Comment by 4383** [comment]
The advantages to use reno is to split ChangeLog by items like:
- features
- fixes
- etc...

**Comment by 4383** [comment]
@rhatdan I'll measure the needed works to introduce that in python-podman

**Pull request closed without merging**
