### PR TITLE
Synchronize with libpod 1.6.1

### PR DESCRIPTION
**Pull request by 4383**
Make python-podman compatible with libpod 1.6.1
    
libpod 1.6.1 is revision is f3ffda1e08f19e9a6a88484136b5eed76533f21a
    
Get diff with:
    
```
$ ./tools/synchronize.sh -b=f3ffda1e08f19e9a6a88484136b5eed76533f21a -i
```

For more infos about this previous command please see #71 
    
Introducing:

- GetContainersByStatus
- HealthCheckRun
- GetContainersByContext
- GetContainersLogs
- GetContainerStatsWithHistory
- InitContainer
- AttachControl
- GetPodsByStatus
- ImageExists
- ContainerExists
- ContainerCheckpoint
- ContainerRestore
- ContainerRunlabel
- ExecContainer
- ListContainerMounts
- MountContainer
- UnmountContainer
- ImagesPrune
- GenerateKube
- ContainerConfig
- ContainerArtifacts
- ContainerInspectData
- ContainerStateData
- PodStateData
- CreateFromCC
- ReceiveFile
- VolumeCreate
- VolumeRemove
- GetVolumes
- VolumesPrune
- ImageSave
- GetPodsByContext
- LoadImage
- GetEvents
- GetLayersMapWithImageInfo
- BuildImageHierarchyMap

Some methods are for the development of Podman and should not be used.

List of ignored and not implemented methods:
- CreateFromCC
- GetLayersMapWithImageInfo
- BuildImageHierarchyMap

When these changes will be merged then we need to release a new python-podman version 1.6.1:

```
$ git tag 1.6.1
$ git push --tags
$ # The previous command will launch the CI who will generate and publish the release 1.6.1 on pypi
```
When these changes will be merged and the tag published then I will do the same things for higher version (1.6.2, 1.6.3, etc... 1.7.0), to ensure that will only release the right delta between versions.

### CODE REVIEW

**Comment by 4383** [comment]
Hello @rhatdan 

Are you (I mean the podman team) interested by these changes?

Please, let me know if we want to continue with these changes.

Thanks

PS: I hope you don't feel harassed, it's not my goal :)

**Comment by rhatdan** [comment]
These LGTM

Most of the team is concentrating on APIV2 which is a replacement for the varlink API.  And some effort is going into podman-py.

**Comment by rhatdan** [comment]
@jwhonce PTAL

**Comment by jwhonce** [comment]
@4383 Changes look good.  But travis shows we are having a dependency issue. Looks like we need a replacement for PyYAML. Do you have any suggestions on that?

**Comment by jwhonce** [comment]
@rhatdan If we drop RHEL7 support would be another way to resolve the dependency issue.

**Comment by 4383** [comment]
Thanks @rhatdan and @jwhonce for you feedback and sorry to disturb you during parallel effort.

Concerning the CI issue it's related to the support of py34, that I think could be dropped, so yes dropping the RHEL7 support which iirc isn't really an issue for podman (integrate to RHEL8) could fix the issue and reduce our footprint in term of python support.

**Comment by rhatdan** [comment]
Yeesh, tough to drop support for RHEL7/Centos7.  Do you know if those distros could get updated versions of python3, so they could use the tools?

**Comment by 4383** [comment]
> Yeesh, tough to drop support for RHEL7/Centos7. Do you know if those distros could get updated versions of python3, so they could use the tools?

@rhatdan sorry no idea

**Comment by h-vetinari** [comment]
> @rhatdan: Do you know if those distros could get updated versions of python3, so they could use the tools?

Very easily, just `yum install rh-python36` (assuming the required optional rpms have been enabled). [Here's](https://developers.redhat.com/blog/2018/08/13/install-python3-rhel/) a blogpost (by RH no less) about the details.

Similarly on [Centos7](https://linuxize.com/post/how-to-install-python-3-on-centos-7/).

**Comment by jwhonce** [comment]
@4383 Do you want to add links to those blogs to the end of the README.md? Otherwise, I will.

**Comment by jwhonce** [comment]
@4383 Do you want to add links to those blogs to the end of the README.md? Otherwise, I will.

**Comment by 4383** [comment]
> @4383 Do you want to add links to those blogs to the end of the README.md? Otherwise, I will.

@jwhonce: As you want, feel free to do it, I'm currently a little bit stuck on other topics.

**Comment by jwhonce** [comment]
@4383 I'll do an additional PR to update README.md after this merges.  LGTM, ready?

**Comment by 4383** [comment]
> @4383 I'll do an additional PR to update README.md after this merges. LGTM, ready?

@jwhonce From my point of view yes it's ready, now you need to judge if  these changes seems ok for you.

Thanls

**Comment by 4383** [comment]
Do you think it's possible to merge these changes?

On [tobiko](https://opendev.org/x/tobiko/) we need some methods implemented by these changes.

We waiting for your feedback.

**Pull request merged**
